export const users = [
    {
        userName: "admin",
        email: "admin@example.com",
        password: "admin123",
        role: "Admin",
    },
    {
        userName: "john_doe",
        email: "john.doe@example.com",
        password: "password123",
        role: "User",
    },
    {
        userName: "jane_doe",
        email: "jane.doe@example.com",
        password: "password123",
        role: "User",
    },
    {
        userName: "alice_smith",
        email: "alice.smith@example.com",
        password: "password123",
        role: "User",
    },
    {
        userName: "bob_jones",
        email: "bob.jones@example.com",
        password: "password123",
        role: "User",
    },
];

export const movies = [
    {
        id: 1,
        title: "Freaks Out (2021)",
        trailerSrc: "https://www.youtube.com/embed/D8La5G1DzCM",
        duration: "141 min",
        releaseYear: 2021,
        ratingImdb: 7.4,
        description:
            "Matilde, Cencio, Fulvio, and Mario are united when World War II strikes Rome. Israel, their circus owner, disappears in an attempt to find a place abroad for all of them.",
        photoSrc: "http://localhost:4000/images/movies/1TkkTo8UiRl5lWM5qkAISHXg0fU.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/1TkkTo8UiRl5lWM5qkAISHXg0fU.jpg",
    },
    {
        id: 2,
        title: "My Father's Violin (2022)",
        trailerSrc: "https://www.youtube.com/embed/GAmo87Ep-tI",
        duration: "112 min",
        releaseYear: 2022,
        ratingImdb: 6.5,
        description:
            "Through their shared grief and connection to music, an orphaned girl bonds with her emotionally distant, successful violinist uncle.",
        photoSrc: "http://localhost:4000/images/movies/fathersviolin.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/fathersviolin.jpg",
    },
    {
        id: 3,
        title: "The Invisible Guest (2016)",
        trailerSrc: "https://www.youtube.com/embed/epCg2RbyF80",
        duration: "126 min",
        releaseYear: 2016,
        ratingImdb: 8.1,
        description:
            "A young businessman faces a lawyer in an attempt to prove his innocence for the murder of his girlfriend.",
        photoSrc: "http://localhost:4000/images/movies/8c9fce3c0ffa46576423d44b525447edc25f1396.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/8c9fce3c0ffa46576423d44b525447edc25f1396.jpg",
    },
    {
        id: 4,
        title: "Blood and Bone (2009)",
        trailerSrc: "https://www.youtube.com/embed/KyOtQr5u-uY",
        duration: "93 min",
        releaseYear: 2009,
        ratingImdb: 6.7,
        description:
            "Ex-con Boun is the new force on the underground street fighting scene in Los Angeles. When he defeats the reigning champion, the local gangster boss wants to enlist Boun in a series of high-stakes international matches. Boun's refusal sets off an explosive showdown between two powerful enemies risking everything.",
        photoSrc: "http://localhost:4000/images/movies/5254_1_ladsfgfdgdfgdfgfdgfdgrge.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/5254_1_ladsfgfdgdfgdfgfdgfdgrge.jpg",
    },
    {
        id: 5,
        title: "SpiderMan No Way Home (2021)",
        trailerSrc: "https://www.youtube.com/embed/JfVOs4VSpmA",
        duration: "148 min",
        releaseYear: 2021,
        ratingImdb: 8.7,
        description:
            "Peter Parker is unmasked and no longer able to separate his normal life from the high stakes of being a Super Hero. When he seeks help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        photoSrc: "http://localhost:4000/images/movies/1gxZrx9gL9ov2c1NpXimEUzMTmh.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/1gxZrx9gL9ov2c1NpXimEUzMTmh.jpg",
    },
    {
        id: 6,
        title: "Iron Will (1994)",
        trailerSrc: "https://www.youtube.com/embed/giLeHfkJeXU",
        duration: "108 min",
        releaseYear: 1994,
        ratingImdb: 6.6,
        description:
            "After his father's death, the responsibility to care for the family falls on Will's shoulders. He enters a dog race that requires long hours of racing and a steely will to win.",
        photoSrc: "http://localhost:4000/images/movies/6Ujbtp0NklUoQ67s32HyW6R5540.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/6Ujbtp0NklUoQ67s32HyW6R5540.jpg",
    },
    {
        id: 7,
        title: "Panama (2022)",
        trailerSrc: "https://www.youtube.com/embed/2GSzkfe1aAY",
        duration: "94 min",
        releaseYear: 2022,
        ratingImdb: 0,
        description:
            "A former marine is hired by a defense contractor to travel to Panama to complete an arms deal. During the process, he becomes involved in the U.S. invasion of Panama and learns an important lesson about the true nature of political power.",
        photoSrc: "http://localhost:4000/images/movies/82I3tDsGDTMy7lHar84Gz0jUuyW.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/82I3tDsGDTMy7lHar84Gz0jUuyW.jpg",
    },
    {
        id: 8,
        title: "Eternals (2021)",
        trailerSrc: "https://www.youtube.com/embed/x_me3xsvDgk",
        duration: "156 min",
        releaseYear: 2021,
        ratingImdb: 6.8,
        description:
            "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they must reunite against mankind's oldest enemy.",
        photoSrc: "http://localhost:4000/images/movies/1RjyfPLsZTq3lUdJY7pTzcmpPKl.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/1RjyfPLsZTq3lUdJY7pTzcmpPKl.jpg",
    },
    {
        id: 9,
        title: "Money Trap (2019)",
        trailerSrc: "https://www.youtube.com/embed/gcH0KPQVVH4",
        duration: "121 min",
        releaseYear: 2019,
        ratingImdb: 6,
        description:
            "Asim Noyan deceives people with his lies and games. Asim Noyan and his gang, whom no one else has been able to capture, get involved in another scam.",
        photoSrc: "http://localhost:4000/images/movies/4kiVg3QJQghjtRupyfWYI3T1R0O-1.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/4kiVg3QJQghjtRupyfWYI3T1R0O-1.jpg",
    },
    {
        id: 10,
        title: "Inch'Allah (2012)",
        trailerSrc: "https://www.youtube.com/embed/53XLPquQD6Q",
        duration: "102 min",
        releaseYear: 2012,
        ratingImdb: 6.8,
        description:
            "A Canadian doctor finds her sympathies severely tested while working in the conflict-ravaged Palestinian territories.",
        photoSrc: "http://localhost:4000/images/movies/9BCd5LdVHQmWqEnDTJ5Ut8idstP-1.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/9BCd5LdVHQmWqEnDTJ5Ut8idstP-1.jpg",
    },
    {
        id: 11,
        title: "Mobile Suit Gundam: Hathaway (2021)",
        trailerSrc: "https://www.youtube.com/embed/MzxnPP5TLeU",
        duration: "95 min",
        releaseYear: 2021,
        ratingImdb: 6.6,
        description:
            "Hathaway Noa becomes part of a terrorist organization called Mufti that organizes an attack on Earth Federation ministers.",
        photoSrc: "http://localhost:4000/images/movies/6gw8onh4FKsruBA7Oouv01EFxzn-1.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/6gw8onh4FKsruBA7Oouv01EFxzn-1.jpg",
    },
    {
        id: 12,
        title: "Rescued by Ruby (2022)",
        trailerSrc: "https://www.youtube.com/embed/-Pwxr307O4w",
        duration: "90 min",
        releaseYear: 2022,
        ratingImdb: 7.3,
        description:
            "Pursuing his dream to join an elite K-9 unit, a state trooper partners with a smart but unruly shelter dog named Ruby.",
        photoSrc: "http://localhost:4000/images/movies/ruby.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/ruby.jpg",
    },
    {
        id: 13,
        title: "The Girl on the Mountain (2022)",
        trailerSrc: "https://www.youtube.com/embed/Y0vh8jQ7HMQ",
        duration: "94 min",
        releaseYear: 2022,
        ratingImdb: 6.4,
        description:
            "When an isolated forester finds a mute little girl wandering alone in the woods, he must protect her from the evil forces determined to end her life.",
        photoSrc: "http://localhost:4000/images/movies/1ZiZ3eVUWPxJROTkYbH8FBC9UuB.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/1ZiZ3eVUWPxJROTkYbH8FBC9UuB.jpg",
    },
    {
        id: 14,
        title: "The Weekend Away (2022)",
        trailerSrc: "https://www.youtube.com/embed/XpfjN-7Hf-8",
        duration: "89 min",
        releaseYear: 2022,
        ratingImdb: 5.6,
        description:
            "A weekend getaway to Croatia goes awry when a woman is accused of murdering her best friend. As she attempts to clear her name and uncover the truth, her efforts reveal a painful secret.",
        photoSrc: "http://localhost:4000/images/movies/6MS0QEl7UK2gdFFbHfNwuYlsq4H.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/6MS0QEl7UK2gdFFbHfNwuYlsq4H.jpg",
    },
    {
        id: 15,
        title: "Black Crab (2022)",
        trailerSrc: "https://www.youtube.com/embed/fmjKsL_-rfw",
        duration: "114 min",
        releaseYear: 2022,
        ratingImdb: 5.7,
        description:
            "In a post-apocalyptic world, six soldiers on a covert mission must transport a mysterious package across a frozen archipelago.",
        photoSrc: "http://localhost:4000/images/movies/blackcrab.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/blackcrab.jpg",
    },
    {
        id: 16,
        title: "The Extra Man (2010)",
        trailerSrc: "https://www.youtube.com/embed/etxKmplTT9Q",
        duration: "108 min",
        releaseYear: 2010,
        ratingImdb: 5.8,
        description: "A man who escorts wealthy women in Manhattan takes a young man under his wing.",
        photoSrc: "http://localhost:4000/images/movies/7RhiXoCm6yEflHQvYtoLeAkDhaU.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/7RhiXoCm6yEflHQvYtoLeAkDhaU.jpg",
    },
    {
        id: 17,
        title: "14 Peaks: Nothing Is Impossible (2021)",
        trailerSrc: "https://www.youtube.com/embed/8QH5hBOoz08",
        duration: "101 min",
        releaseYear: 2021,
        ratingImdb: 7.8,
        description:
            "Fearless Nepali mountaineer Nirmal Purja embarks on a seemingly impossible quest to summit all 14 of the world's 8,000-meter peaks in seven months.",
        photoSrc: "http://localhost:4000/images/movies/beyondpossible.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/beyondpossible.jpg",
    },
    {
        id: 18,
        title: "The Innocents (2021)",
        trailerSrc: "https://www.youtube.com/embed/T8HR-zTRrCM",
        duration: "117 min",
        releaseYear: 2021,
        ratingImdb: 7,
        description:
            "During the long days of the polar summer, a group of children reveal their dark and mysterious powers while the adults aren't watching. This playtime takes a dangerous turn.",
        photoSrc: "http://localhost:4000/images/movies/4hIptu4Yre7pIUhFa7GBZlfDTPW.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/4hIptu4Yre7pIUhFa7GBZlfDTPW.jpg",
    },
    {
        id: 19,
        title: "Mean Dreams (2016)",
        trailerSrc: "https://www.youtube.com/embed/jNOAVTX8PPE",
        duration: "108 min",
        releaseYear: 2016,
        ratingImdb: 6.1,
        description:
            "A 15-year-old boy steals a bag of drug money and runs off with the girl he loves. As her violent and corrupt police officer father hunts them down, they embark on a journey that will change their lives forever.",
        photoSrc: "http://localhost:4000/images/movies/AlowOYyprAAq85PPtE9LvoiYT1b.jpg",
        photoSrcProd:
            "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/movies/AlowOYyprAAq85PPtE9LvoiYT1b.jpg",
    },
];

export const series = [
    {
        id: 1,
        title: "Rebelde",
        trailerSrc: "https://www.youtube.com/watch?v=BJYJksHREIc",
        description:
            "Rebelde follows the lives of students at Elite Way School, a prestigious private school in Mexico City.",
        releaseYear: 2022,
        ratingImdb: 6.3,
        photoSrc: "http://localhost:4000/images/series/rebelde.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/rebelde.jpg",
    },
    {
        id: 2,
        title: "Snowfall",
        trailerSrc: "https://www.youtube.com/embed/BJYJksHREIc",
        description:
            "Snowfall is an American television series created by John Singleton, Eric Amadio, and Dave Andron. The series is set in the early 1980s in Los Angeles and examines the early days of the crack cocaine epidemic and its impact.",
        releaseYear: 2017,
        ratingImdb: 8.2,
        photoSrc: "http://localhost:4000/images/series/snowfall.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/snowfall.jpg",
    },
    {
        id: 3,
        title: "Man vs Bee",
        trailerSrc: "https://www.youtube.com/embed/BJYJksHREIc",
        description:
            "Man vs Bee is a documentary series that explores the confrontation between plants and bees in our world.",
        releaseYear: 2022,
        ratingImdb: 6.8,
        photoSrc: "http://localhost:4000/images/series/manbee.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/manbee.jpg",
    },
    {
        id: 4,
        title: "Moonknight",
        trailerSrc: "https://www.youtube.com/embed/x7Krla_UxRg",
        description:
            "Moonknight follows the adventures of Marc Spector, a former military man who gains powers from a mythological being.",
        releaseYear: 2022,
        ratingImdb: 7.4,
        photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/moonknight.jpg",
    },
    {
        id: 5,
        title: "Peacemaker",
        trailerSrc: "https://www.youtube.com/embed/WHXq62VCaCM",
        description:
            "Peacemaker is an American television series created by James Gunn for the DC Universe and HBO Max.",
        releaseYear: 2022,
        ratingImdb: 8.3,
        photoSrc: "http://localhost:4000/images/series/peacemaker.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/peacemaker.jpg",
    },
    {
        id: 6,
        title: "Top Boy",
        trailerSrc: "https://www.youtube.com/embed/BYLYZ7OsymE",
        description:
            "Top Boy is a British television series created by Ronan Bennet. The series follows the lives of teenagers and those involved in drug trafficking in a poor neighborhood in London.",
        releaseYear: 2011,
        ratingImdb: 8.4,
        photoSrc: "http://localhost:4000/images/series/topboy.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/topboy.jpg",
    },
    {
        id: 7,
        title: "Ganglands",
        trailerSrc: "https://www.youtube.com/embed/0VZ2Nbx8gHI",
        description:
            "Ganglands is a French crime series based on the true story of a family running an organized crime gang in Paris.",
        releaseYear: 2021,
        ratingImdb: 7.0,
        photoSrc: "http://localhost:4000/images/series/ganglands.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/ganglands.jpg",
    },
    {
        id: 8,
        title: "Ozark",
        trailerSrc: "https://www.youtube.com/embed/5hAXVqrljbs",
        description:
            "Ozark is an American drama series that follows the life of a family that develops a large money-laundering business in the Ozark Mountains in Missouri.",
        releaseYear: 2017,
        ratingImdb: 8.5,
        photoSrc: "http://localhost:4000/images/series/ozark.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/ozark.jpg",
    },
    {
        id: 9,
        title: "Resident Alien",
        trailerSrc: "https://www.youtube.com/embed/T4J7QjGNTs4",
        description:
            "Resident Alien is an American sci-fi comedy series that follows an extraterrestrial trying to escape his secret identity by living as a doctor in a small American town.",
        releaseYear: 2021,
        ratingImdb: 8.1,
        photoSrc: "http://localhost:4000/images/series/alien.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/alien.jpg",
    },
    {
        id: 10,
        title: "Bridgerton",
        trailerSrc: "https://www.youtube.com/embed/U4JYAx5rNRA",
        description:
            "Bridgerton is a British-American historical drama series created by Chris Van Dusen and produced by Shonda Rhimes. The series follows the lives of the Bridgerton family in London from 1813-1827.",
        releaseYear: 2020,
        ratingImdb: 7.3,
        photoSrc: "http://localhost:4000/images/series/bridgerton.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/bridgerton.jpg",
    },
    {
        id: 11,
        title: "Superman & Lois",
        trailerSrc: "https://www.youtube.com/embed/SJPJPUpNvDw",
        description:
            "Superman & Lois is an American superhero television series based on the DC Comics characters Superman and Lois Lane. The series follows the lives of Superman and Lois Lane after their marriage, facing challenges in both their personal lives and their profession as superheroes.",
        releaseYear: 2021,
        ratingImdb: 7.8,
        photoSrc: "http://localhost:4000/images/series/superman.jpg",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/superman.jpg",
    },
    {
        id: 12,
        title: "Attack on Titan",
        trailerSrc: "https://www.youtube.com/embed/MGRm4IzK1SQ",
        description:
            "Attack on Titan is a Japanese anime series based on the manga of the same name written by Hajime Isayama. The series follows the story of a world where human civilization is threatened by giant creatures known as Titans.",
        releaseYear: 2013,
        ratingImdb: 9.0,
        photoSrc: "http://localhost:4000/images/series/aot.png",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/aot.png",
    },
    {
        id: 13,
        title: "Kengan Ashura",
        trailerSrc: "https://www.youtube.com/embed/CNuY4ymi4Fs",
        description:
            "Kengan Ashura is a Japanese anime series based on the manga of the same name written by Yabako Sandrovich. The series follows the story of Tokita Ohma, a young fighter involved in a combat tournament called Kengan to dominate the business of firms.",
        releaseYear: 2019,
        ratingImdb: 8.0,
        photoSrc: "http://localhost:4000/images/series/baki.png",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/baki.png",
    },
    {
        id: 14,
        title: "Elite",
        trailerSrc: "https://www.youtube.com/embed/QNwhAdrdwp0",
        description:
            "Elite is a Spanish series created by Carlos Montero and Darío Madrona. The series follows the lives of students at a high-end private school in Spain, where tragic events and various secrets come to light.",
        releaseYear: 2018,
        ratingImdb: 7.4,
        photoSrc: "http://localhost:4000/images/series/elite.png",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/elite.png",
    },
    {
        id: 15,
        title: "The Flash",
        trailerSrc: "https://www.youtube.com/embed/hebWYacbdvc",
        description:
            "The Flash is an American superhero television series created by Greg Berlanti, Andrew Kreisberg, and Geoff Johns, based on the DC Comics character of the same name. The series follows the adventures of Barry Allen, a forensic scientist who gains the ability to move at incredible speeds after a lab accident.",
        releaseYear: 2014,
        ratingImdb: 7.6,
        photoSrc: "http://localhost:4000/images/series/flash.png",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/flash.png",
    },
    {
        id: 16,
        title: "Power Book IV: Force",
        trailerSrc: "https://www.youtube.com/embed/uiGzLrJSk8E",
        description:
            'Power Book IV: Force is an American drama series created by Courtney A. Kemp for Starz. The series follows the life of Tommy Egan, a character first introduced in the series "Power", as he becomes involved in the world of organized crime in Chicago.',
        releaseYear: 2022,
        ratingImdb: 8.1,
        photoSrc: "http://localhost:4000/images/series/force.png",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/force.png",
    },
    {
        id: 17,
        title: "Halo",
        trailerSrc: "https://www.youtube.com/embed/5KZ3MKraNKY",
        description:
            'Halo is an American sci-fi television series created by Kyle Killen and Steven Kane. Based on the popular "Halo" video game by Microsoft Studios, the series follows the adventures of Master Chief, a super-soldier called upon to protect a harsh world from the threat of an alien alliance known as the Covenant.',
        releaseYear: 2022,
        ratingImdb: 7.0,
        photoSrc: "http://localhost:4000/images/series/halo.png",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/halo.png",
    },
    {
        id: 18,
        title: "The Last Kingdom",
        trailerSrc: "https://www.youtube.com/embed/BJYJksHREIc",
        description:
            'The Last Kingdom is a British historical series created by Stephen Butchard. Based on the "Saxon Stories" novels by Bernard Cornwell, the series follows the adventures of Uhtred Ragnarson, a Saxon boy who attempts to defend and reclaim his territory in Middle Britain in the 9th century.',
        releaseYear: 2015,
        ratingImdb: 8.5,
        photoSrc: "http://localhost:4000/images/series/thelastkingdom.png",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/thelastkingdom.png",
    },
    {
        id: 19,
        title: "Knightfall",
        trailerSrc: "https://www.youtube.com/embed/F9dtepkeR0I",
        description:
            "Knightfall is an American historical drama series created by Don Handfield and Richard Rayner for the History Channel. The series follows the rise and fall of the Knights Templar, beginning with its foundation in post-war Selma, Alabama, in 1865, to its suppression in 1871.",
        releaseYear: 2017,
        ratingImdb: 6.7,
        photoSrc: "http://localhost:4000/images/series/knightfall.png",
        photoSrcProd: "https://movielandia-fgyorwoem-avenger22s-projects.vercel.app/images/series/knightfall.png",
    },
];

export const genres = [
    { id: 1, name: "Action" },
    { id: 2, name: "Asian" },
    { id: 3, name: "Crime" },
    { id: 4, name: "Netflix" },
    { id: 5, name: "Horror" },
    { id: 6, name: "Thriller" },
    { id: 7, name: "Fantasy" },
    { id: 8, name: "Sci-Fi" },
    { id: 9, name: "Drama" },
    { id: 10, name: "Spanish" },
    { id: 11, name: "Adventure" },
    { id: 12, name: "Comedy" },
    { id: 13, name: "History" },
    { id: 14, name: "War" },
    { id: 15, name: "Russian" },
    { id: 16, name: "Romance" },
    { id: 17, name: "Biography" },
    { id: 18, name: "Italian" },
    { id: 19, name: "Mystery" },
    { id: 20, name: "Sport" },
    { id: 21, name: "Family" },
    { id: 22, name: "Music" },
    { id: 23, name: "Animation" },
    { id: 24, name: "Erotic +18" },
    { id: 25, name: "Nordic" },
    { id: 26, name: "Documentary" },
    { id: 27, name: "Turkish" },
    { id: 28, name: "COMING SOON" },
    { id: 29, name: "German" },
    { id: 30, name: "French" },
    { id: 31, name: "Hindi" },
];

export const movieGenres = [
    { movieId: 1, genreId: 1 },
    { movieId: 1, genreId: 2 },
    { movieId: 2, genreId: 3 },
    { movieId: 2, genreId: 4 },
    { movieId: 2, genreId: 5 },
    { movieId: 3, genreId: 6 },
    { movieId: 3, genreId: 7 },
    { movieId: 4, genreId: 8 },
    { movieId: 4, genreId: 9 },
    { movieId: 4, genreId: 10 },
    { movieId: 5, genreId: 11 },
    { movieId: 5, genreId: 12 },
    { movieId: 5, genreId: 13 },
    { movieId: 6, genreId: 14 },
    { movieId: 6, genreId: 15 },
    { movieId: 6, genreId: 16 },
    { movieId: 7, genreId: 17 },
    { movieId: 7, genreId: 18 },
    { movieId: 7, genreId: 19 },
    { movieId: 8, genreId: 20 },
    { movieId: 8, genreId: 21 },
    { movieId: 8, genreId: 22 },
    { movieId: 9, genreId: 23 },
    { movieId: 9, genreId: 24 },
    { movieId: 10, genreId: 25 },
    { movieId: 11, genreId: 26 },
    { movieId: 11, genreId: 27 },
    { movieId: 11, genreId: 28 },
    { movieId: 11, genreId: 29 },
    { movieId: 12, genreId: 30 },
    { movieId: 13, genreId: 31 },
    { movieId: 14, genreId: 3 },
    { movieId: 15, genreId: 1 },
    { movieId: 15, genreId: 2 },
    { movieId: 15, genreId: 3 },
    { movieId: 15, genreId: 4 },
    { movieId: 15, genreId: 5 },
    { movieId: 16, genreId: 6 },
    { movieId: 16, genreId: 7 },
    { movieId: 16, genreId: 8 },
    { movieId: 16, genreId: 9 },
    { movieId: 16, genreId: 10 },
    { movieId: 17, genreId: 11 },
    { movieId: 17, genreId: 12 },
    { movieId: 18, genreId: 13 },
    { movieId: 18, genreId: 14 },
    { movieId: 19, genreId: 15 },
    { movieId: 19, genreId: 16 },
    { movieId: 19, genreId: 17 },
];

export const serieGenres = [
    { serieId: 1, genreId: 1 },
    { serieId: 1, genreId: 2 },
    { serieId: 1, genreId: 3 },
    { serieId: 2, genreId: 4 },
    { serieId: 2, genreId: 5 },
    { serieId: 3, genreId: 6 },
    { serieId: 3, genreId: 7 },
    { serieId: 5, genreId: 8 },
    { serieId: 4, genreId: 9 },
    { serieId: 6, genreId: 10 },
    { serieId: 6, genreId: 11 },
    { serieId: 6, genreId: 12 },
    { serieId: 6, genreId: 13 },
    { serieId: 7, genreId: 14 },
    { serieId: 7, genreId: 15 },
    { serieId: 7, genreId: 16 },
    { serieId: 7, genreId: 17 },
    { serieId: 8, genreId: 18 },
    { serieId: 10, genreId: 19 },
    { serieId: 9, genreId: 20 },
    { serieId: 11, genreId: 21 },
    { serieId: 12, genreId: 22 },
    { serieId: 13, genreId: 23 },
    { serieId: 14, genreId: 24 },
    { serieId: 15, genreId: 25 },
    { serieId: 16, genreId: 26 },
    { serieId: 17, genreId: 27 },
    { serieId: 18, genreId: 28 },
    { serieId: 19, genreId: 29 },
    { serieId: 19, genreId: 30 },
    { serieId: 19, genreId: 31 },
    { serieId: 19, genreId: 5 },
];

// export const episodes = [
//     {
//         id: 1,
//         title: "Snowfall Sezoni 1 Episodi 1",
//         description:
//             "Sipërmarrësi i rrugës nga qendra jugore Franklin Saint bën një hap në lojën e kokainës. Oficeri i pakënaqur i CIA-s, Teddy McDonald, bën aleancë me një ushtar Contra. Mundësi Luchador, Gustavo El Oso Zapata hyn në një familje karteli meksikan.'.",
//         photoSrc: "http://localhost:4000/images/rsz_fistful_of_vengeance.png",
//         videoSrc: "//vidmoly.net/embed-09lyu1ioabwf.html",
//         seasonId: 1,
//     },
//     {
//         id: 2,
//         title: "Snowfall Sezoni 1 Episodi 2",
//         description:
//             "Franklin vazhdon punën e tij korrier për Avi-n. Takimi i parë i Tedit me Avin nuk pritet. Gustavo mëson se nga kush vodhi - dhe përfundoi duke u vrarë në një pushtim në shtëpi..",
//         photoSrc: "http://localhost:4000/images/series/snowfall.jpg",
//         videoSrc: "//vidmoly.net/embed-09lyu1ioabwf.html",
//         seasonId: 1,
//     },
//     {
//         id: 3,
//         title: "Origin Sezoni 1 Episodi 1",
//         description:
//             "Kai Jin, një kuzhinier i ri në San Francisko, ngatërrohet me ndjekjen e Triadës Kineze për fuqitë e lashta vdekjeprurëse të njohura si 'Wu Xing'.",
//         photoSrc: "http://localhost:4000/images/rsz_fistful_of_vengeance.png",
//         videoSrc: "//vidmoly.net/embed-09lyu1ioabwf.html",
//         seasonId: 1,
//     },
// ];

// export const seasons = [
//     {
//         id: 1,
//         title: "Rebelde - Season 1",
//         photoSrc: "http://localhost:4000/images/series/rebelde.jpg",
//         releaseYear: 2022,
//         ratingImdb: 6.5,
//         serieId: 1,
//     },
//     {
//         id: 2,
//         title: "Snowfall - Season 1",
//         photoSrc: "http://localhost:4000/images/series/snowfall.jpg",
//         releaseYear: 2017,
//         ratingImdb: 8.0,
//         serieId: 2,
//     },
//     {
//         id: 3,
//         title: "Man vs Bee - Season 1",
//         photoSrc: "http://localhost:4000/images/series/manbee.jpg",
//         releaseYear: 2022,
//         ratingImdb: 7.5,
//         serieId: 3,
//     },
//     {
//         id: 4,
//         title: "Moonknight - Season 1",
//         photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
//         releaseYear: 2022,
//         ratingImdb: 9.0,
//         serieId: 4,
//     },
//     {
//         id: 5,
//         title: "Peacemaker - Season 1",
//         photoSrc: "http://localhost:4000/images/series/peacemaker.jpg",
//         releaseYear: 2022,
//         ratingImdb: 7.5,
//         serieId: 5,
//     },
//     {
//         id: 6,
//         title: "Snowfall - Season 2",
//         photoSrc: "http://localhost:4000/images/series/snowfall.jpg",
//         releaseYear: 2021,
//         ratingImdb: 7.8,
//         serieId: 2,
//     },
//     {
//         id: 7,
//         title: "Moonknight - Season 2",
//         photoSrc: "http://localhost:4000/images/series/moonknight.jpg",
//         releaseYear: 2021,
//         ratingImdb: 8.2,
//         serieId: 4,
//     },
// ];
