export const movies = [
    {
        title: 'Freaks Out (2021)',
        trailerSrc: 'https://www.youtube.com/embed/D8La5G1DzCM',
        duration: '141 min',
        releaseYear: 2021,
        ratingImdb: 7.4,
        description:
            'Matilde, Cencio, Fulvio dhe Mario janë të bashkuar kur Lufta e Dytë Botërore godet Romën. Izraeli, pronari i cirkut të tyre, zhduket në përpjekje për të gjetur një vend jashtë shtetit për të gjithë. ',
        photoSrc: 'http://localhost:4000/images/1TkkTo8UiRl5lWM5qkAISHXg0fU.jpg',
    },

    {
        title: 'My Father&#8217;s Violin (2022) a.k.a Babamin Kemani',
        trailerSrc: 'https://www.youtube.com/embed/GAmo87Ep-tI',
        duration: '112 min',
        releaseYear: 2022,
        ratingImdb: 6.5,
        description:
            'Përmes pikëllimit të tyre të përbashkët dhe lidhjes me muzikën, një vajzë jetime lidhet me xhaxhain e saj violinist të suksesshëm emocionalisht të përmbajtur. ',
        photoSrc:
            'http://localhost:4000/images/AAAABUDmZc0IlYhKxh_DwvPU7qvpsrbSoCgyCEq-B_W552mUo5Qd6IYm9cf6WdfcyfccLK3qumrjgGbpid6I72Y4CVi-eVA-sy8XRgUxF4I41MOefi0gwN-mAYog9fhe1g.jpg',
    },
    {
        title: 'The Invisible Guest (2016) a.k.a Contratiempo',
        trailerSrc: 'https://www.youtube.com/embed/epCg2RbyF80',
        duration: '126 min',
        releaseYear: 2016,
        ratingImdb: 8.1,
        description:
            'Nje biznesmen i ri perballet me nje avokat ne perpjekje per te provuar pafajesine per vrasjen e te dashures se tij.',
        photoSrc: 'http://localhost:4000/images/8c9fce3c0ffa46576423d44b525447edc25f1396.jpg',
    },
    {
        title: 'Blood and Bone (2009)',
        trailerSrc: 'https://www.youtube.com/embed/KyOtQr5u-uY',
        duration: '93 min',
        releaseYear: 2009,
        ratingImdb: 6.7,
        description:
            'Ish i dënuari Boun është forca e re në skenën e ndeshjeve të fshehta te rrugëve në Los Anxheles. Kur ai mund kampionin në fuqi, bosi i gangsterëve vendas dëshiron që ta fusë Bounin në një seri ndeshjesh ndërkombëtare me fitime të mëdha. Refuzimi i Bounit nis një shfaqje shpërthyese midis dy armiqve të fuqishëm që po rrezikojnë gjithçka.',
        photoSrc: 'http://localhost:4000/images/5254_1_ladsfgfdgdfgdfgfdgfdgrge.jpg',
    },
    {
        title: 'Spider-Man: No Way Home (2021)',
        trailerSrc: 'https://www.youtube.com/embed/JfVOs4VSpmA',
        duration: '148 min',
        releaseYear: 2021,
        ratingImdb: 8.7,
        description:
            'Peter Parker është i demaskuar dhe nuk është më në gjendje të ndajë jetën e tij normale nga rreziku i të qenit një Super Hero. Kur ai kërkon ndihmë nga Doctor Strange, rreziku shtohet, duke e detyruar atë të zbulojë se çfarë do të thotë me të vërtetë të jesh Spider-Man.',
        photoSrc: 'http://localhost:4000/images/1gxZrx9gL9ov2c1NpXimEUzMTmh.jpg',
    },
    {
        title: 'Iron Will (1994)',
        trailerSrc: 'https://www.youtube.com/embed/giLeHfkJeXU',
        duration: '108 min',
        releaseYear: 1994,
        ratingImdb: 6.6,
        description:
            "Pas vdekjes së babait të tij, përgjegjësia për t'u kujdesur për familjen bie mbi supet e Will. Ai merr pjesë në një garë me qen, e cila kërkon orë të gjata garash dhe një vullnet të hekurt për të fituar. ",
        photoSrc: 'http://localhost:4000/images/6Ujbtp0NklUoQ67s32HyW6R5540.jpg',
    },
    {
        title: 'Panama (2022)',
        trailerSrc: 'https://www.youtube.com/embed/2GSzkfe1aAY',
        duration: '94 min',
        releaseYear: 2022,
        ratingImdb: 0,
        description:
            'Një ish-marins punësohet nga një kontraktues i mbrojtjes për të udhëtuar në Panama për të mbyllur një marrëveshje armësh. Në këtë proces ai përfshihet me pushtimin e Panamasë nga SHBA dhe nxjerr një mësim të rëndësishëm për natyrën e vërtetë të pushtetit politik. ',
        photoSrc: 'http://localhost:4000/images/82I3tDsGDTMy7lHar84Gz0jUuyW.jpg',
    },
    {
        title: 'Eternals (2021)',
        trailerSrc: 'https://www.youtube.com/embed/x_me3xsvDgk',
        duration: '156 min',
        releaseYear: 2021,
        ratingImdb: 6.8,
        description:
            'Të përjetshmit janë një skuadër jashtëtokësorësh të lashtë që kanë jetuar në Tokë në fshehtësi për mijëra vjet. Kur një tragjedi e papritur i detyron të dalin nga hija, ata duhet të ribashkohen kundër armikut më të lashtë të njerëzimit…',
        photoSrc: 'http://localhost:4000/images/1RjyfPLsZTq3lUdJY7pTzcmpPKl.jpg',
    },
    {
        title: 'Money Trap (2019) a.k.a. Organize Isler: Sazan Sarmali',
        trailerSrc: 'https://www.youtube.com/embed/gcH0KPQVVH4',
        duration: '121 min',
        releaseYear: 2019,
        ratingImdb: 6,
        description:
            "Asim Noyan mashtron njerëzit me gënjeshtrat dhe lojërat e tij. Asim Noyan-i dhe banda e tij, të cilët askush tjetër nuk ka mundur t'i kapë, ngatërrohet përsëri në një mashtrim. ",
        photoSrc: 'http://localhost:4000/images/4kiVg3QJQghjtRupyfWYI3T1R0O-1.jpg',
    },
    {
        title: 'Inch&#8217;Allah (2012)',
        trailerSrc: 'https://www.youtube.com/embed/53XLPquQD6Q',
        duration: '102 min',
        releaseYear: 2012,
        ratingImdb: 6.8,
        description:
            'Një mjeke kanadeze i gjen simpatitë e saj të testuara rëndë ndërsa punonte në territoret palestineze të shkatërruara nga konflikti. ',
        photoSrc: 'http://localhost:4000/images/9BCd5LdVHQmWqEnDTJ5Ut8idstP-1.jpg',
    },
    {
        title: 'Mobile Suit Gundam: Hathaway (2021)',
        trailerSrc: 'https://www.youtube.com/embed/MzxnPP5TLeU',
        duration: '95 min',
        releaseYear: 2021,
        ratingImdb: 6.6,
        description:
            'Hathauej Noa, bëhet pjesë e një organizate terroriste e quajtur Mufti i cili organizon një sulm ndaj ministrave të Federatës së Tokës. ',
        photoSrc: 'http://localhost:4000/images/6gw8onh4FKsruBA7Oouv01EFxzn-1.jpg',
    },
    {
        title: 'Rescued by Ruby (2022)',
        trailerSrc: 'https://www.youtube.com/embed/-Pwxr307O4w',
        duration: '90 min',
        releaseYear: 2022,
        ratingImdb: 7.3,
        description:
            "Duke ndjekur ëndrrën e tij për t'u bashkuar me njësinë elitare të K-9, një ushtarak i shtetit bashkëpunon me një qen strehe shumë të zgjuar por të pabindur, Rubin. ",
        photoSrc:
            'http://localhost:4000/images/AAAABRFlUGzasg1we4oVLLc9JXVq7ZSQLn7HdWN843xQeoxnJ-Ls416_Fd9MxwwWpQRVluHj3dYxFCFqxorgsuRN1eG8U8KnhpwcWXWV8z8d_BRv7u-_8SNe_1qEByE-Ow.jpg',
    },
    {
        title: 'The Girl on the Mountain (2022)',
        trailerSrc: 'https://www.youtube.com/embed/Y0vh8jQ7HMQ',
        duration: '94 min',
        releaseYear: 2022,
        ratingImdb: 6.4,
        description:
            "Kur një pylltar i izoluar gjen një vajzë të vogël memece që endet vetëm në pyll, ai duhet ta mbrojë atë nga forcat e liga të vendosura për t'i dhënë fund jetës së saj. ",
        photoSrc: 'http://localhost:4000/images/1ZiZ3eVUWPxJROTkYbH8FBC9UuB.jpg',
    },
    {
        title: 'The Weekend Away (2022)',
        trailerSrc: 'https://www.youtube.com/embed/XpfjN-7Hf-8',
        duration: '89 min',
        releaseYear: 2022,
        ratingImdb: 5.6,
        description:
            'Një fundjavë pushimi në Kroaci shkon keq kur një grua akuzohet për vrasjen e shoqes së saj më të mirë. Ndërsa përpiqet të pastrojë emrin e saj dhe të zbulojë të vërtetën, përpjekjet e saj zbulojnë një sekret të dhimbshëm. ',
        photoSrc: 'http://localhost:4000/images/6MS0QEl7UK2gdFFbHfNwuYlsq4H.jpg',
    },
    {
        title: 'Black Crab (2022) a.k.a. Svart krabba',
        trailerSrc: 'https://www.youtube.com/embed/fmjKsL_-rfw',
        duration: '114 min',
        releaseYear: 2022,
        ratingImdb: 5.7,
        description:
            'Në një botë post-apokaliptike, gjashtë ushtarë në një mision të fshehtë duhet të transportojnë një paketë misterioze nëpër një arkipelag të ngrirë. ',
        photoSrc:
            'http://localhost:4000/images/AAAABRpgAjiXoh3YCHvnc31BeBIIV-l3PFksMA7KkJpdGMG5UpOieHhdRKz5-itmm8LK_yEJaJbI7LdIrs9jB2k-AvD4K7mldJenJoRZ4RVY8OKBrwICoEkVCj96XhvlKA.jpg',
    },
    {
        title: 'The Extra Man (2010)',
        trailerSrc: 'https://www.youtube.com/embed/etxKmplTT9Q',
        duration: '108 min',
        releaseYear: 2010,
        ratingImdb: 5.8,
        description: 'Një burrë që shoqëron gra të pasura në Manhatan merr një djalë të ri në patronazh. ',
        photoSrc: 'http://localhost:4000/images/7RhiXoCm6yEflHQvYtoLeAkDhaU.jpg',
    },
    {
        title: '14 Peaks: Nothing Is Impossible (2021)',
        trailerSrc: 'https://www.youtube.com/embed/8QH5hBOoz08',
        duration: '101 min',
        releaseYear: 2021,
        ratingImdb: 7.8,
        description:
            'Alpinisti i patrembur nepalez Nirmal Purxha, nis një kërkim në dukje të pamundur për të arritur të 14 majat 8 mijë metra të botës në 7 muaj. ',
        photoSrc:
            'http://localhost:4000/images/AAAABdM8h2pl06NCiYL3_uSQ53x2O_kxCWz5cpJKX251-TFv35GWncYZjdbxfDmJwhda2SHLeIJCer_pCm90RxKgA1i4e2rLrHDNr94BhEFRa8QeeaxfEi80nsltpV95DQ.jpg',
    },
    {
        title: 'The Innocents (2021) a.k.a. De uskyldige',
        trailerSrc: 'https://www.youtube.com/embed/T8HR-zTRrCM',
        duration: '117 min',
        releaseYear: 2021,
        ratingImdb: 7,
        description:
            'Gjatë kohës së dritave polare një grup fëmijësh zbulojnë fuqitë e tyre të errëta dhe misterioze ndërkohë që të rriturit nuk i shohin, por kjo lojë merr një kthesë të rrezikshme. ',
        photoSrc: 'http://localhost:4000/images/4hIptu4Yre7pIUhFa7GBZlfDTPW.jpg',
    },
    {
        title: 'Mean Dreams (2016)',
        trailerSrc: 'https://www.youtube.com/embed/jNOAVTX8PPE',
        duration: '108 minuta',
        releaseYear: 2016,
        ratingImdb: 6.1,
        description:
            "'Ëndrra të Këqija' : Një djalë 15-vjeçar vjedh një çantë me para droge dhe ia mbath me vajzën që dashuron. Ndërkohë që babai i saj polic, i dhunshëm dhe i korruptuar i ndjek, ata nisen në një udhëtim që do ju ndryshojë jetën përgjithmonë. ",
        photoSrc: 'http://localhost:4000/images/AlowOYyprAAq85PPtE9LvoiYT1b.jpg',
    },
];

export const movieGenres = [
    [1, 2, 3, 4],
    [5, 3, 4, 6],
    [1, 7, 8],
    [1, 9, 6],
    [1, 10, 6],
    [11, 12, 3, 10],
    [3, 10, 6],
    [1, 9, 13, 14, 15],
    [8, 12],
    [1, 16, 10, 6],
    [9, 5, 6],
    [17, 9, 13],
    [9, 12, 16],
    [11, 9, 8, 18],
    [1, 2, 9, 3],
    [2, 9, 3],
    [5, 19, 6],
    [3, 20, 6],
    [9, 21, 22],
    [5],
    [7, 12, 4],
    [16, 6],
    [9, 12],
    [21, 8, 12],
    [11, 8],
    [9, 3, 6],
    [9, 3, 6],
    [23, 11, 12],
    [9, 3, 6],
    [9, 24, 25],
    [9, 6],
    [9],
    [9, 12, 16],
    [9, 19, 6],
    [1, 2, 3, 6],
    [1, 3, 6],
    [6],
    [12, 16],
    [1, 6],
    [9, 3, 16],
    [17, 9, 20],
    [9, 7, 5],
    [9, 3, 10, 6],
    [11, 9],
    [26, 4],
    [11, 9, 21],
    [9, 8, 16],
    [7, 6],
    [9, 7, 16],
    [9, 4, 27],
    [1, 9, 3],
    [12, 4],
    [3, 19, 6],
    [8, 12],
    [9, 20],
    [17, 9, 20],
    [12, 16, 27],
    [17, 13, 14, 15],
    [28],
    [11, 2, 13],
    [12, 16],
    [9, 16],
    [2, 7, 6],
    [9, 12, 4, 16],
    [1, 9, 6],
    [9, 13, 16],
    [11, 7, 15, 6],
    [11, 9, 13, 4],
    [5, 6],
    [3, 19, 10, 6],
    [29, 12],
    [1, 30, 3, 6],
    [1, 17, 9, 14, 4],
    [1, 23, 11, 2],
    [30, 12],
    [4, 16, 27],
    [1, 12, 14],
    [1, 2, 9, 14],
    [9, 5],
    [12, 4, 20],
    [1, 3],
    [17, 9, 3],
    [9, 31, 3, 19],
    [31, 12],
    [1, 2, 9, 13, 14],
    [1, 6],
    [1, 11, 9],
    [9, 3, 6],
    [9, 7],
    [1, 11, 7],
    [1, 11, 7],
    [5, 12, 6],
    [2, 9, 19, 6],
    [12, 16],
    [5, 19, 6],
    [1, 9, 3],
    [1, 11, 9, 31],
    [30, 5, 6],
    [9, 16],
    [5, 19, 6],
    [1, 11, 12],
    [9, 19, 6],
    [11, 21],
    [1, 9, 6],
    [1, 9, 7],
    [5, 12, 19],
    [2, 9, 3],
    [9, 3, 6],
    [10, 6],
    [1, 3, 6],
    [1, 2, 6],
    [1, 11, 8],
    [17, 9],
    [11, 21, 8],
    [28],
    [28],
    [28],
    [28],
    [28],
    [28],
    [28],
    [28],
    [28],
    [28],
    [28],
    [28],
    [23, 11, 12],
    [28],
    [1, 29, 6],
    [9, 13, 15],
    [9, 12, 3],
    [2, 9, 12, 3],
    [1, 11, 17],
    [9, 12],
    [9, 24, 6],
    [1, 2, 12],
    [1, 11, 12],
    [8, 5, 19],
    [12, 4, 16],
    [11, 12, 3],
    [1, 14],
    [1, 11, 9],
    [1, 2, 9, 5],
    [9, 5],
    [9, 24],
    [1, 9, 25, 6],
    [1, 9, 20],
    [1, 9, 3],
    [11, 8],
    [9, 5, 6],
    [1, 11, 2, 4],
    [9, 5, 6],
    [12, 22, 16],
    [9, 12],
    [9, 12],
    [1, 11, 12, 4],
    [1, 9, 6],
    [1, 9, 3],
    [1, 11],
    [1, 23, 11],
    [9, 31, 3, 6],
    [12, 16],
    [9, 12],
    [9, 5],
    [9, 16],
    [23, 11, 12],
    [1, 20],
    [11, 21],
    [9, 18, 3],
    [1, 6],
    [1, 11, 8],
    [9, 4],
    [12, 4, 27],
    [9, 19, 6],
    [12],
    [17, 9, 4],
    [11, 9, 13],
    [11, 5, 12],
    [5, 6],
    [1, 5],
    [9, 31, 3, 16],
    [1, 9, 6],
    [1, 26, 12],
    [1, 9, 30, 12],
    [11, 24],
    [9, 13, 14, 25],
    [5, 19, 6],
    [8, 5, 19],
    [9],
    [23, 2, 4],
    [12, 4, 16, 10],
    [9, 12, 3],
    [17, 9, 21, 4],
    [9, 6],
    [9],
    [1, 4, 16],
    [9, 19],
    [9, 13, 3, 4, 25],
    [9, 21, 12],
    [5, 19, 6],
    [9, 14],
    [9, 3, 19, 4],
    [9, 3, 19],
    [11, 21, 12],
    [1, 2, 12],
    [1, 12, 3],
    [11, 21],
    [9, 5, 19],
    [1, 9, 20],
    [1, 11, 6],
    [1, 11, 12],
    [5],
    [1, 19, 6],
    [9, 7, 6],
    [9, 3, 6],
    [9, 21, 22],
    [1, 11, 4, 25],
    [9, 3, 6],
    [1, 11, 7],
    [1, 2, 3, 6],
    [1, 2, 9, 14],
    [1, 9, 13, 15],
    [1, 2, 3, 6],
    [9],
    [12],
    [12],
    [12, 3],
    [12],
    [31, 3, 19, 6],
    [1, 18, 3, 19],
    [9, 4, 16, 27],
    [11, 21, 30, 12],
    [1, 9, 6],
    [12],
    [9, 25, 6],
    [9, 19, 6],
    [9, 3, 4, 6],
    [23, 21, 12],
    [1, 9, 6],
    [8, 12, 16],
    [12, 4, 16],
    [1, 3, 20],
    [1, 11, 8],
    [1, 14, 15],
    [5, 6],
    [9, 7],
    [1, 9, 7],
    [11, 26, 4, 20],
    [1, 12, 3],
    [1, 11, 7],
    [9],
    [1, 7, 19],
    [12, 3],
    [1, 2, 9, 14],
    [9, 5, 19, 4],
    [9, 5, 19],
    [9, 12, 16],
    [26, 3, 4],
    [1, 7],
    [17, 9, 22],
    [9, 12],
    [18, 12],
    [1, 12, 3],
    [9, 5, 19, 25],
    [1, 5, 6],
    [6],
    [1, 2, 3],
    [1, 9, 3],
    [1, 9, 13, 14],
    [21, 12, 4, 27],
    [9, 3],
    [1, 11, 9],
    [17, 9, 13],
    [9, 19, 16],
    [9, 27],
    [9, 16, 27],
    [23, 21, 12],
    [8, 5, 6],
    [1, 12, 3],
    [12],
    [1, 11, 9],
    [9, 16],
    [9, 19, 6],
    [5, 6],
    [1, 11, 5],
    [1, 11, 4, 10],
    [1, 3, 10, 6],
    [1, 9, 3],
    [9, 3],
    [28],
    [1, 12, 3],
    [9],
    [1, 2, 9, 3],
    [17, 9],
    [1, 11, 7],
    [1, 30, 12],
    [1, 9, 13],
    [9, 5, 19],
    [1, 3, 6],
    [18, 12],
    [2, 9],
    [1, 3, 6],
    [1, 9, 7],
    [17, 9, 31],
    [9],
    [1, 2, 9, 8],
];

export const genres = [
    { name: 'Aksion' },
    { name: 'Aziatik' },
    { name: 'Krim' },
    { name: 'NETFLIX' },
    { name: 'Horror' },
    { name: 'Thriller' },
    { name: 'Fantashkencë' },
    { name: 'Fantazi' },
    { name: 'Dramë' },
    { name: 'Spanjoll' },
    { name: 'Aventurë' },
    { name: 'Komedi' },
    { name: 'Histori' },
    { name: 'Luftë' },
    { name: 'Rus' },
    { name: 'Romancë' },
    { name: 'Biografi' },
    { name: 'Italian' },
    { name: 'Mister' },
    { name: 'Sport' },
    { name: 'Familjar' },
    { name: 'Muzikë' },
    { name: 'Animuar' },
    { name: 'Erotik +18' },
    { name: 'Nordik' },
    { name: 'Dokumentar' },
    { name: 'Turk' },
    { name: 'SË SHPEJTI' },
    { name: 'Gjerman' },
    { name: 'Francez' },
    { name: 'Hindi' },
];

export const series = [
    {
        id: 1,
        title: 'Rebelde',
        releaseYear: 2022,
        ratingImdb: 6.3,
        photoSrc: 'http://localhost:4000/images/series/rebelde.jpg',
    },
    {
        id: 2,
        title: 'Snowfall',
        releaseYear: 2017,
        ratingImdb: 8.2,
        photoSrc: 'http://localhost:4000/images/series/snowfall.jpg',
    },
    {
        id: 3,
        title: 'Man vs Bee',
        releaseYear: 2022,
        ratingImdb: 6.8,
        photoSrc: 'http://localhost:4000/images/series/manbee.jpg',
    },
    {
        id: 4,
        title: 'Moonknight',
        releaseYear: 2022,
        ratingImdb: 7.4,
        photoSrc: 'http://localhost:4000/images/series/moonknight.jpg',
    },
    {
        id: 5,
        title: 'Peacemaker',
        releaseYear: 2022,
        ratingImdb: 8.3,
        photoSrc: 'http://localhost:4000/images/series/peacemaker.jpg',
    },
    {
        id: 6,
        title: 'Top Boy',
        releaseYear: 2011,
        ratingImdb: 8.4,
        photoSrc: 'http://localhost:4000/images/series/topboy.jpg',
    },
    {
        id: 7,
        title: 'Ganglands',
        releaseYear: 2021,
        ratingImdb: 7.0,
        photoSrc: 'http://localhost:4000/images/series/ganglands.jpg',
    },
    {
        id: 8,
        title: 'Ozark',
        releaseYear: 2017,
        ratingImdb: 8.5,
        photoSrc: 'http://localhost:4000/images/series/ozark.jpg',
    },
    {
        id: 9,
        title: 'Resident Alien',
        releaseYear: 2021,
        ratingImdb: 8.1,
        photoSrc: 'http://localhost:4000/images/series/alien.jpg',
    },
    {
        id: 10,
        title: 'Bridgerton',
        releaseYear: 2020,
        ratingImdb: 7.3,
        photoSrc: 'http://localhost:4000/images/series/bridgerton.jpg',
    },
    {
        id: 11,
        title: 'Superman & Lois',
        releaseYear: 2021,
        ratingImdb: 7.8,
        photoSrc: 'http://localhost:4000/images/series/superman.jpg',
    },
    {
        id: 12,
        title: 'Attack on Titan',
        releaseYear: 2013,
        ratingImdb: 9.0,
        photoSrc: 'http://localhost:4000/images/series/aot.png',
    },
    {
        id: 13,
        title: 'Kengan Ashura',
        releaseYear: 2019,
        ratingImdb: 8.0,
        photoSrc: 'http://localhost:4000/images/series/baki.png',
    },
    {
        id: 14,
        title: 'Elite',
        releaseYear: 2018,
        ratingImdb: 7.4,
        photoSrc: 'http://localhost:4000/images/series/elite.png',
    },
    {
        id: 15,
        title: 'The Flash',
        releaseYear: 2014,
        ratingImdb: 7.6,
        photoSrc: 'http://localhost:4000/images/series/flash.png',
    },
    {
        id: 16,
        title: 'Power Book IV: Force',
        releaseYear: 2022,
        ratingImdb: 8.1,
        photoSrc: 'http://localhost:4000/images/series/force.png',
    },
    {
        id: 17,
        title: 'Halo',
        releaseYear: 2022,
        ratingImdb: 7.0,
        photoSrc: 'http://localhost:4000/images/series/halo.png',
    },
    {
        id: 18,
        title: 'The Last Kingdom',
        releaseYear: 2015,
        ratingImdb: 8.5,
        photoSrc: 'http://localhost:4000/images/series/kingdom.png',
    },
    {
        id: 19,
        title: 'Knightfall',
        releaseYear: 2017,
        ratingImdb: 6.7,
        photoSrc: 'http://localhost:4000/images/series/knightfall.png',
    },
    {
        id: 20,
        title: 'Mocro maffia',
        releaseYear: 2018,
        ratingImdb: 8.2,
        photoSrc: 'http://localhost:4000/images/series/mocromafia.png',
    },
    {
        id: 21,
        title: 'Origin',
        releaseYear: 2018,
        ratingImdb: 7.0,
        photoSrc: 'http://localhost:4000/images/series/origin.png',
    },
    {
        id: 22,
        title: 'Peaky Blinders',
        releaseYear: 2013,
        ratingImdb: 8.8,
        photoSrc: 'http://localhost:4000/images/series/peaky.png',
    },
    {
        id: 23,
        title: 'Queen of the South',
        releaseYear: 2016,
        ratingImdb: 7.9,
        photoSrc: 'http://localhost:4000/images/series/queensouth.png',
    },
];

export const episodes = [
    {
        id: 1,
        title: 'Snowfall Sezoni 1 Episodi 1',
        description:
            "Sipërmarrësi i rrugës nga qendra jugore Franklin Saint bën një hap në lojën e kokainës. Oficeri i pakënaqur i CIA-s, Teddy McDonald, bën aleancë me një ushtar Contra. Mundësi Luchador, Gustavo El Oso Zapata hyn në një familje karteli meksikan.'.",
        photoSrc: 'http://localhost:4000/images/rsz_fistful_of_vengeance.png',
        videoSrc: '//vidmoly.net/embed-09lyu1ioabwf.html',
        seasonId: 1,
    },
    {
        id: 2,
        title: 'Snowfall Sezoni 1 Episodi 2',
        description:
            'Franklin vazhdon punën e tij korrier për Avi-n. Takimi i parë i Tedit me Avin nuk pritet. Gustavo mëson se nga kush vodhi - dhe përfundoi duke u vrarë në një pushtim në shtëpi..',
        photoSrc: 'http://localhost:4000/images/series/snowfall.jpg',
        videoSrc: '//vidmoly.net/embed-09lyu1ioabwf.html',
        seasonId: 1,
    },
    {
        id: 3,
        title: 'Origin Sezoni 1 Episodi 1',
        description:
            "Kai Jin, një kuzhinier i ri në San Francisko, ngatërrohet me ndjekjen e Triadës Kineze për fuqitë e lashta vdekjeprurëse të njohura si 'Wu Xing'.",
        photoSrc: 'http://localhost:4000/images/rsz_fistful_of_vengeance.png',
        videoSrc: '//vidmoly.net/embed-09lyu1ioabwf.html',
        seasonId: 1,
    },
];

export const seasons = [
    {
        id: 1,
        title: 'Rebelde - Season 1',
        photoSrc: 'http://localhost:4000/images/series/rebelde.jpg',
        releaseYear: 2022,
        ratingImdb: 6.5,
        serieId: 1,
    },
    {
        id: 2,
        title: 'Snowfall - Season 1',
        photoSrc: 'http://localhost:4000/images/series/snowfall.jpg',
        releaseYear: 2017,
        ratingImdb: 8.0,
        serieId: 2,
    },
    {
        id: 3,
        title: 'Man vs Bee - Season 1',
        photoSrc: 'http://localhost:4000/images/series/manbee.jpg',
        releaseYear: 2022,
        ratingImdb: 7.5,
        serieId: 3,
    },
    {
        id: 4,
        title: 'Moonknight - Season 1',
        photoSrc: 'http://localhost:4000/images/series/moonknight.jpg',
        releaseYear: 2022,
        ratingImdb: 9.0,
        serieId: 4,
    },
    {
        id: 5,
        title: 'Peacemaker - Season 1',
        photoSrc: 'http://localhost:4000/images/series/peacemaker.jpg',
        releaseYear: 2022,
        ratingImdb: 7.5,
        serieId: 5,
    },
    {
        id: 6,
        title: 'Snowfall - Season 2',
        photoSrc: 'http://localhost:4000/images/series/snowfall.jpg',
        releaseYear: 2021,
        ratingImdb: 7.8,
        serieId: 2,
    },
    {
        id: 7,
        title: 'Moonknight - Season 2',
        photoSrc: 'http://localhost:4000/images/series/moonknight.jpg',
        releaseYear: 2021,
        ratingImdb: 8.2,
        serieId: 4,
    },
];
